routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::prefix('content')->name('content.')->group(function () {
    Route::get('{page}', 'ContentController@index')->name('index');
    Route::get('{page}/create', 'ContentController@create')->name('create');
    Route::post('{page}', 'ContentController@store')->name('store');
    Route::get('{page}/{content}/edit', 'ContentController@edit')->name('edit');
    Route::put('{page}/{content}', 'ContentController@update')->name('update');
    Route::delete('{page}/{content}', 'ContentController@destroy')->name('destroy');
});

//Bind Route
Route::resource('language', 'LanguageController');
Route::resource('page', 'PageController');
Route::resource('role', 'RoleController');
Route::resource('user', 'UserController');
Route::resource('category', 'CategoryController');
Route::resource('news', 'NewsController');
Route::resource('position', 'PositionController');
Route::resource('image', 'ImageController');
Route::resource('cart', 'CartController');
Route::resource('province', 'ProvinceController');
Route::resource('district', 'DistrictController');
Route::resource('ward', 'WardController');
Route::resource('producer', 'ProducerController');
Route::resource('attribute', 'AttributeController');
Route::resource('product', 'ProductController');
Route::resource('backup', 'BackupController')->except(['edit', 'update', 'show']);
Route::resource('activity', 'LogActivityController')->only(['index', 'destroy']);
Route::get('backup/download/{backup}','BackupController@download')->name('backup.download');

Route::prefix('config')->name('config.')->group(function () {
    Route::get('/', 'ConfigController@edit')->name('edit');
    Route::put('update', 'ConfigController@update')->name('update');
});

Route::prefix('page')->name('page.')->group(function () {
    Route::get('page-translation/{page}', 'PageController@language')->name('language');
    Route::post('page-translation/{page}', 'PageController@translation')->name('translation');
});

Route::prefix('content')->name('content.')->group(function () {
    Route::get('translation/{page}/{content}', 'ContentController@language')->name('language');
    Route::post('translation/{page}/{content}', 'ContentController@translation')->name('translation');
});

Route::prefix('category')->name('category.')->group(function () {
    Route::get('translation/{category}', 'CategoryController@language')->name('language');
    Route::post('translation/{category}', 'CategoryController@translation')->name('translation');
});

Route::prefix('image')->name('image.')->group(function () {
    Route::get('translation/{image}', 'ImageController@language')->name('language');
    Route::post('translation/{image}', 'ImageController@translation')->name('translation');
});

Route::prefix('producer')->name('producer.')->group(function () {
    Route::get('translation/{producer}', 'ProducerController@language')->name('language');
    Route::post('translation/{producer}', 'ProducerController@translation')->name('translation');
});

Route::prefix('attribute')->name('attribute.')->group(function () {
    Route::get('translation/{attribute}', 'AttributeController@language')->name('language');
    Route::post('translation/{attribute}', 'AttributeController@translation')->name('translation');
});

Route::prefix('news')->name('news.')->group(function () {
    Route::get('translation/{news}', 'NewsController@language')->name('language');
    Route::post('translation/{news}', 'NewsController@translation')->name('translation');
    Route::get('detail/{news}', 'NewsController@detail')->name('detail');
    Route::get('seo/{news}', 'NewsController@seo')->name('seo');
});

Route::prefix('product')->name('product.')->group(function () {
    Route::get('translation/{product}', 'ProductController@language')->name('language');
    Route::post('translation/{product}', 'ProductController@translation')->name('translation');
});

Route::prefix('contact')->name('contact.')->group(function () {
    Route::get('/', 'ReplyContactController@index')->name('index');
    Route::get('reply/{contact}', 'ReplyContactController@reply')->name('reply');
    Route::post('reply/{contact}', 'ReplyContactController@send_reply')->name('send_reply');
    Route::delete('reply/{contact}', 'ReplyContactController@destroy')->name('destroy');
});

Route::prefix('personal')->name('personal.')->group(function () {
    Route::get('/', 'PersonalController@show')->name('show');
    Route::put('update-account', 'PersonalController@update_account')->name('update_account');
    Route::put('update-avatar', 'PersonalController@update_avatar')->name('update_avatar');
    Route::put('update-info', 'PersonalController@update_info')->name('update_info');
    Route::get('logout', 'PersonalController@logout')->name('logout');
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    //Bind Datatables
    Route::get('role-datatables', 'RoleController@dataTableIndex')->name('roleDataTables');
    Route::get('user-datatables', 'UserController@dataTableIndex')->name('userDataTables');
    Route::get('language-datatables', 'LanguageController@dataTableIndex')->name('languageDataTables');
    Route::get('personal-datatables', 'PersonalController@dataTableIndex')->name('personalDataTables');
    Route::get('get-cart', 'CartController@dataTableIndex')->name('CartController');
    Route::get('news-datatables', 'NewsController@dataTableIndex')->name('newsDataTables');
    Route::get('images-datatables', 'ImageController@dataTableIndex')->name('imageDataTables');
    Route::get('page-datatables', 'PageController@dataTableIndex')->name('pageDataTables');
    Route::get('contact-datatables', 'ReplyContactController@dataTableIndex')->name('contactDataTables');
    Route::get('content-datatables/{page}', 'ContentController@dataTableIndex')->name('contentDataTables');
    Route::get('activity-datatables', 'LogActivityController@dataTableIndex')->name('activityDataTables');
    Route::get('province-datatables', 'ProvinceController@dataTableIndex')->name('provinceDataTables');
    Route::get('district-datatables', 'DistrictController@dataTableIndex')->name('districtDataTables');
    Route::get('ward-datatables', 'WardController@dataTableIndex')->name('wardDataTables');
    Route::get('producer-datatables', 'ProducerController@dataTableIndex')->name('producerDataTables');
    Route::get('attribute-datatables', 'AttributeController@dataTableIndex')->name('attributeDataTables');
    Route::get('product-datatables', 'ProductController@dataTableIndex')->name('productDataTables');
    Route::post('get-district-by-province', 'WardController@loadDistrict')->name('loadDistrict');

    Route::post('select-category-position', 'CategoryController@ajaxSelectCategory')->name('ajaxSelectCategory');
    Route::put('table-category-position', 'CategoryController@ajaxTableCategory')->name('ajaxTableCategory');
    Route::post('select-position-position', 'PositionController@ajaxSelectPosition')->name('ajaxSelectPosition');
    Route::put('table-position-position', 'PositionController@ajaxTablePosition')->name('ajaxTablePosition');
    Route::post('select-position-image', 'ImageController@ajaxSelectPositionImages')->name('ajaxSelectPositionImages');
    Route::post('select-attribute-position', 'AttributeController@ajaxSelectAttribute')->name('ajaxSelectAttribute');

    Route::post('add-notification','AjaxController@addNotification')->name('addNotification');
    Route::post('make-as-read','AjaxController@MakeAsReadNoti')->name('MakeAsReadNoti');
    Route::post('add-row-upload-image', 'AjaxController@addRowUploadImage')->name('addRowUploadImage');
    Route::post('add-row-upload-attribute', 'AjaxController@addRowUploadAttribute')->name('addRowUploadAttribute');
    Route::post('get-district', 'AjaxController@getDistrict')->name('getDistrict');
    Route::post('get-ward', 'AjaxController@getWard')->name('getWard');
});

Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('lang/{locale}', 'DashboardController@locale')->name('locale');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')->name('ckfinder_connector');
Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')->name('ckfinder_browser');

Route::get('/', function () {
    $data['config'] = DB::table('configs')->pluck('value', 'attribute')->toArray();
    // dd(file_get_contents(base_path("route/admin.php")));
    return view('welcome',$data);
})->name('index');

Route::get('/orderId/{orderid}',function () {
    $data['config'] = DB::table('configs')->pluck('value', 'attribute')->toArray();
    return view('welcome',$data);
})->name('orderId');
Route::get('/payment_success', 'TestPayment@getStatusCode')->name('pay_success');

Route::post('/created_order','TestPayment@createOrder')->name('created_order');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Rennokki\QueryCache\Traits\QueryCacheable;
use Askedio\SoftCascade\Traits\SoftCascadeTrait;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;

class Product extends BaseModel implements TranslatableContract
{
    use SoftDeletes, Translatable, SoftCascadeTrait, QueryCacheable;

    /**
     * The table associated with the model.
     * @var string
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    protected $table = 'products';

    public $cacheFor = 3600; // equivalent of ->cacheFor(3600)

    /**
     * equivalent of ->cacheTags(['products'])
     * @var string
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
    */
    public $cacheTags = ['products'];
    /**
     * equivalent of ->cachePrefix('products_');
     * @var string
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
    */
    public $cachePrefix = 'products_';
    /**
     * Invalidate the cache automatically
     * upon update in the database.
     *
     * @var bool
     */
    protected static $flushCacheOnUpdate = true;

    /**
     * The attributes that aren't mass assignable.
     * @var array
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    protected $guarded = [];

    /**
     * The attributes that should be mutated to dates.
     * @var array
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    protected $dates = ['created_at', 'updated_at'];

    /**
     * The attributes soft delete with function name.
     * @var array
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    protected $softCascade = ['product_translation', 'product_images', 'category_product'];

    /**
     * The attributes translate language.
     * @var array
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public $translatedAttributes = ['name', 'quantity', 'promotion_id', 'price', 'discount', 'description', 'content', 'image', 'youtube', 'file', 'slug', 'title_tag', 'meta_keywords', 'meta_description', 'locale', 'product_id'];

    /**
     * The auto generate uuid
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->uuid = (string) Str::uuid();
        });
    }

    /**
     * Relationship with translation
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function product_translation()
    {
        return $this->hasMany(ProductTranslation::class);
    }

    /**
     * The category that belong to the news.
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function category()
    {
        return $this->belongsToMany(Category::class, 'category_products');
    }

    /**
     * The category that belong to the product.
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function category_product()
    {
        return $this->hasMany(CategoryProduct::class);
    }

    /**
     * Get the images for the product.
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function product_images()
    {
        return $this->hasMany(ProductImage::class);
    }

    /**
     * Get the attribute for the product.
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function product_attribute()
    {
        return $this->hasMany(ProductAttribute::class);
    }

}

resources/views/administrator/modules/product/actions.blade.php
<div class="list-icons">
    <div class="dropdown">
        <a href="#" class="list-icons-item" data-toggle="dropdown">
            <i class="icon-menu9"></i>
        </a>

        <div class="dropdown-menu dropdown-menu-right">
            @can('product_edit')
                <a href="{{ route('admin.product.edit', ['product' => $uuid]) }}" class="dropdown-item text-info"><i class="icon-pencil"></i> {{ behavior('action.edit') }}</a>
            @endcan

            @can('product_destroy')
                <a href="{{ route('admin.product.destroy', ['product' => $uuid]) }}" class="dropdown-item accept_delete text-danger"><i class="icon-trash"></i> {{ behavior('action.delete') }}</a>
            @endcan

            @if (config('app.multi_language'))
                @can('category_create')
                    @php
                        $translate = $product->translateRemaining($uuid)
                    @endphp

                    @if ($translate["full"])
                        <a class="dropdown-item"><i class="icon-earth"></i>{{ behavior('action.language') }} {!! $translate['language'] !!}</a>
                    @else
                        <a href="{{ route('admin.product.language', ['product' => $uuid]) }}" class="dropdown-item"><i class="icon-earth"></i>{{ behavior('action.language') }} {!! $translate['language'] !!}</a>
                    @endif
                @endcan
            @endif

        </div>
    </div>
</div>

resources/views/administrator/modules/product/create.blade.php
@extends('administrator.master')
@section('module', module('product'))
@section('action', behavior('action.create'))
@section('title', title_module('product','create'))

@canany(['product_index', 'product_edit', 'product_destroy'])
    @section('index', route('admin.product.index'))
@endcanany

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'ui/dragula.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'media/fancybox.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/inputs/maxlength.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/tags/tokenfield.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/switch.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'editors/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/bootstrap_multiselect.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'ui/moment/moment.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'pickers/pickadate/picker.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'pickers/pickadate/picker.date.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'extensions/jquery_ui/widgets.min.js') }}"></script>
    @include('ckfinder::setup')
@endpush

@section('content')
    <form action="{{ route('admin.product.store') }}" method="POST" enctype="multipart/form-data" class="formAjax">
        @csrf
        @method('POST')

        <div class="row">
            @include('administrator.partials.button', ['exit' => route('admin.product.index')])

            <div class="col-lg-8">
                <div class="card">
                    <div class="card-header bg-transparent border-bottom header-elements-inline">

                        <h6 class="card-title">{{ behavior('action.info') }}</h6>

                        <div class="header-elements">
                            <div class="list-icons">
                                <a class="list-icons-item" data-action="collapse"></a>
                                <a class="list-icons-item" data-action="fullscreen"></a>
                                <a class="list-icons-item" data-action="remove"></a>
                            </div>
                        </div>
                    </div>

                    <div class="bg-light">
                        <ul class="nav nav-tabs nav-tabs-bottom mb-0">
                            <li class="nav-item">
                                <a href="#card-toolbar-tab1" class="nav-link active" data-toggle="tab">
                                    <i class="icon-cube mr-2"></i>
                                    {{ behavior('action.content') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#card-toolbar-tab2" class="nav-link" data-toggle="tab">
                                    <i class="icon-image2 mr-2"></i>
                                    {{ behavior('action.secondary_image') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#card-toolbar-tab3" class="nav-link" data-toggle="tab">
                                    <i class="icon-eyedropper2 mr-2"></i>
                                    {{ behavior('action.three_attribute') }}
                                </a>
                            </li>
                        </ul>
                    </div>

                    <div class="card-body tab-content" id="forms-target-left">
                        <div class="tab-pane fade show active" id="card-toolbar-tab1">
                            <x-text label="product.name" type="text" name="name" placeholder="product.name" slug="slug_name" title="title_name" required="required">
                                {{ old('name') }}
                            </x-text>

                            <div class="row">
                                <div class="col-lg-6">
                                    <x-text label="product.price" type="text" name="price" placeholder="product.price" required="required">
                                        {{ old('price') }}
                                    </x-text>
                                </div>

                                <div class="col-lg-6">
                                    <x-text label="product.discount" type="text" name="discount" placeholder="product.discount">
                                        {{ old('discount') }}
                                    </x-text>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <x-datetime label="product.date_start" name="date_start" placeholder="product.date_start">
                                        {{ date('d/m/Y',time()) }}
                                    </x-datetime>
                                </div>

                                <div class="col-md-2">
                                    <label>{{ label('product.time_start') }}</label>
                                    <select name="time_start" class="form-control">
                                        {!! time_24_hours() !!}
                                    </select>
                                </div>

                                <div class="col-md-4">
                                    <x-datetime label="product.date_end" name="date_end" placeholder="product.date_end">
                                        {{ date('d/m/Y') }}
                                    </x-datetime>
                                </div>

                                <div class="col-md-2">
                                    <label>{{ label('product.time_end') }}</label>
                                    <select name="time_end" class="form-control">
                                        {!! time_24_hours() !!}
                                    </select>
                                </div>
                            </div>

                            <x-editor label="product.description" name="description" required="required">
                                {{ old('description') }}
                            </x-editor>

                            <x-editor label="product.content" name="content">
                                {{ old('content') }}
                            </x-editor>
                        </div>

                        <div class="tab-pane fade" id="card-toolbar-tab2">
                            <x-images></x-images>
                        </div>

                        <div class="tab-pane fade" id="card-toolbar-tab3">
                            <x-attribute></x-attribute>
                        </div>
                    </div>
                </div>

                <x-card title="action.seo" id="forms-target-left">
                    <x-multiple label="seo.meta_robots" name="meta_robots[]" :dataSelect="robot()" required="required">
                        {{ old('meta_robots','index,follow') }}
                    </x-multiple>

                    <x-multiple label="seo.meta_google_bot" name="meta_google_bot[]" :dataSelect="robot()" required="required">
                        {{ old('meta_google_bot','index,follow') }}
                    </x-multiple>

                    <x-text label="seo.slug" type="text" name="slug" placeholder="seo.slug" id="slug_name" required="required">
                        {{ old('slug') }}
                    </x-text>

                    <x-text label="seo.title_tag" type="text" name="title_tag" placeholder="seo.title_tag" id="title_name" required="required">
                        {{ old('title_tag') }}
                    </x-text>

                    <x-tag label="seo.meta_keywords" name="meta_keywords" placeholder="seo.meta_description">
                        {{ old('meta_keywords') }}
                    </x-tag>

                    <x-description label="seo.meta_description" name="meta_description" placeholder="seo.meta_description">
                        {{ old('meta_description') }}
                    </x-description>
                </x-card>
            </div>

            <div class="col-lg-4">
                <x-card :module="$category_name" id="forms-target-right">
                    @if (count($categories) <= 0)
                        {{ message('product.no_category') }}
                    @else
                        @php
                            recursionList($categories)
                        @endphp
                    @endif
                </x-card>

                <x-card title="action.info" id="forms-target-right">
                    <x-selectbox label="product.producer" name="producer_id" :dataSelect="$producer" required="required">
                        {{ old('producer') }}
                    </x-selectbox>

                    <x-text label="product.position" type="text" name="position" placeholder="product.position" required="required">
                        {{ old('position',$position) }}
                    </x-text>

                    <x-text label="product.viewed" type="text" name="viewed" placeholder="product.viewed" required="required">
                        {{ old('viewed',100) }}
                    </x-text>

                    <x-selectbox label="element.open_link" name="open_link" :dataSelect="open_link()">
                        {{ old('open_link') }}
                    </x-selectbox>

                    <x-selectbox label="product.template" name="template" :dataSelect="template_detail_product()">
                        {{ old('template') }}
                    </x-selectbox>

                    <x-multiple label="element.access" name="access[]" :dataSelect="level()">
                        {{ old('access','1,2') }}
                    </x-multiple>

                    <x-selectbox label="element.status" name="status" :dataSelect="status()">
                        {{ old('status') }}
                    </x-selectbox>

                    <x-multiple label="element.featured" name="featured[]" :dataSelect="featured()">
                        {{ old('featured','1') }}
                    </x-multiple>

                    <x-image name="image">
                        {{ old('image') }}
                    </x-image>

                    <x-youtube name="youtube" label="product.youtube" placeholder="product.youtube">
                        {{ old('youtube') }}
                    </x-youtube>

                    <x-file label="product.file" name="file" placeholder="product.file">
                        {{ old('file') }}
                    </x-file>
                </x-card>
            </div>
        </div>
    </form>
@endsection

resources/views/administrator/modules/product/index.blade.php
@extends('administrator.master')
@section('module', module('product'))
@section('action', behavior('action.index'))
@section('title', title_module('product','index'))

@can('product_create')
    @section('create',route('admin.product.create'))
@endcan

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/extensions/buttons.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/extensions/responsive.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
@endpush

@section('content')
    <x-card title="action.info" table="true">
        <table class="table table-hover datatable-colvis-basic" url="{{ route('admin.ajax.productDataTables') }}">
            <thead>
                <tr>
                    <th>{{ label('element.table_id') }}</th>
                    <th>{{ label('product.image') }}</th>
                    <th>{{ label('product.name') }}</th>
                    <th>{{ label('product.category') }}</th>
                    <th>{{ label('element.status') }}</th>
                    <th>{{ label('element.featured') }}</th>
                    @canany(['product_edit', 'product_destroy'])
                        <th class="text-center">{{ label('element.actions') }}</th>
                    @endcanany
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th data="DT_RowIndex" name="DT_RowIndex" orderable="false" searchable="false"></th>
                    <th data="image" name="image"></th>
                    <th type="text" data="name" name="name">{{ label('product.name') }}</th>
                    <th type="select" data="category" name="category">
                        <select class="form-control" name="category">
                            <option value="">{{ label('please_choose') }}</option>
                            @php
                                recursiveSelectDatatable($category, old('category'))
                            @endphp
                        </select>
                    </th>
                    <th type="select" data="status" name="status">
                        <select class="form-control">
                            <option value="">{{ label('please_choose') }}</option>
                            @foreach (status() as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </th>
                    <th type="select" data="featured" name="featured">
                        <select class="form-control">
                            <option value="">{{ label('please_choose') }}</option>
                            @foreach (featured() as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </th>
                    @canany(['product_edit', 'product_destroy'])
                        <th class="text-center" data="actions" name="actions" orderable="false" searchable="false">{{ label('element.actions') }}</th>
                    @endcanany
                </tr>
            </tfoot>
        </table>
    </x-card>
@endsection