routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::prefix('content')->name('content.')->group(function () {
    Route::get('{page}', 'ContentController@index')->name('index');
    Route::get('{page}/create', 'ContentController@create')->name('create');
    Route::post('{page}', 'ContentController@store')->name('store');
    Route::get('{page}/{content}/edit', 'ContentController@edit')->name('edit');
    Route::put('{page}/{content}', 'ContentController@update')->name('update');
    Route::delete('{page}/{content}', 'ContentController@destroy')->name('destroy');
});

//Bind Route
Route::resource('language', 'LanguageController');
Route::resource('page', 'PageController');
Route::resource('role', 'RoleController');
Route::resource('user', 'UserController');
Route::resource('category', 'CategoryController');
Route::resource('news', 'NewsController');
Route::resource('position', 'PositionController');
Route::resource('image', 'ImageController');
Route::resource('cart', 'CartController');
Route::resource('province', 'ProvinceController');
Route::resource('district', 'DistrictController');
Route::resource('ward', 'WardController');
Route::resource('producer', 'ProducerController');
Route::resource('attribute', 'AttributeController');
Route::resource('product', 'ProductController');
Route::resource('backup', 'BackupController')->except(['edit', 'update', 'show']);
Route::resource('activity', 'LogActivityController')->only(['index', 'destroy']);
Route::get('backup/download/{backup}','BackupController@download')->name('backup.download');

Route::prefix('config')->name('config.')->group(function () {
    Route::get('/', 'ConfigController@edit')->name('edit');
    Route::put('update', 'ConfigController@update')->name('update');
});

Route::prefix('page')->name('page.')->group(function () {
    Route::get('page-translation/{page}', 'PageController@language')->name('language');
    Route::post('page-translation/{page}', 'PageController@translation')->name('translation');
});

Route::prefix('content')->name('content.')->group(function () {
    Route::get('translation/{page}/{content}', 'ContentController@language')->name('language');
    Route::post('translation/{page}/{content}', 'ContentController@translation')->name('translation');
});

Route::prefix('category')->name('category.')->group(function () {
    Route::get('translation/{category}', 'CategoryController@language')->name('language');
    Route::post('translation/{category}', 'CategoryController@translation')->name('translation');
});

Route::prefix('image')->name('image.')->group(function () {
    Route::get('translation/{image}', 'ImageController@language')->name('language');
    Route::post('translation/{image}', 'ImageController@translation')->name('translation');
});

Route::prefix('producer')->name('producer.')->group(function () {
    Route::get('translation/{producer}', 'ProducerController@language')->name('language');
    Route::post('translation/{producer}', 'ProducerController@translation')->name('translation');
});

Route::prefix('attribute')->name('attribute.')->group(function () {
    Route::get('translation/{attribute}', 'AttributeController@language')->name('language');
    Route::post('translation/{attribute}', 'AttributeController@translation')->name('translation');
});

Route::prefix('news')->name('news.')->group(function () {
    Route::get('translation/{news}', 'NewsController@language')->name('language');
    Route::post('translation/{news}', 'NewsController@translation')->name('translation');
    Route::get('detail/{news}', 'NewsController@detail')->name('detail');
    Route::get('seo/{news}', 'NewsController@seo')->name('seo');
});

Route::prefix('product')->name('product.')->group(function () {
    Route::get('translation/{product}', 'ProductController@language')->name('language');
    Route::post('translation/{product}', 'ProductController@translation')->name('translation');
});

Route::prefix('contact')->name('contact.')->group(function () {
    Route::get('/', 'ReplyContactController@index')->name('index');
    Route::get('reply/{contact}', 'ReplyContactController@reply')->name('reply');
    Route::post('reply/{contact}', 'ReplyContactController@send_reply')->name('send_reply');
    Route::delete('reply/{contact}', 'ReplyContactController@destroy')->name('destroy');
});

Route::prefix('personal')->name('personal.')->group(function () {
    Route::get('/', 'PersonalController@show')->name('show');
    Route::put('update-account', 'PersonalController@update_account')->name('update_account');
    Route::put('update-avatar', 'PersonalController@update_avatar')->name('update_avatar');
    Route::put('update-info', 'PersonalController@update_info')->name('update_info');
    Route::get('logout', 'PersonalController@logout')->name('logout');
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    //Bind Datatables
    Route::get('role-datatables', 'RoleController@dataTableIndex')->name('roleDataTables');
    Route::get('user-datatables', 'UserController@dataTableIndex')->name('userDataTables');
    Route::get('language-datatables', 'LanguageController@dataTableIndex')->name('languageDataTables');
    Route::get('personal-datatables', 'PersonalController@dataTableIndex')->name('personalDataTables');
    Route::get('get-cart', 'CartController@dataTableIndex')->name('CartController');
    Route::get('news-datatables', 'NewsController@dataTableIndex')->name('newsDataTables');
    Route::get('images-datatables', 'ImageController@dataTableIndex')->name('imageDataTables');
    Route::get('page-datatables', 'PageController@dataTableIndex')->name('pageDataTables');
    Route::get('contact-datatables', 'ReplyContactController@dataTableIndex')->name('contactDataTables');
    Route::get('content-datatables/{page}', 'ContentController@dataTableIndex')->name('contentDataTables');
    Route::get('activity-datatables', 'LogActivityController@dataTableIndex')->name('activityDataTables');
    Route::get('province-datatables', 'ProvinceController@dataTableIndex')->name('provinceDataTables');
    Route::get('district-datatables', 'DistrictController@dataTableIndex')->name('districtDataTables');
    Route::get('ward-datatables', 'WardController@dataTableIndex')->name('wardDataTables');
    Route::get('producer-datatables', 'ProducerController@dataTableIndex')->name('producerDataTables');
    Route::get('attribute-datatables', 'AttributeController@dataTableIndex')->name('attributeDataTables');
    Route::get('product-datatables', 'ProductController@dataTableIndex')->name('productDataTables');
    Route::post('get-district-by-province', 'WardController@loadDistrict')->name('loadDistrict');

    Route::post('select-category-position', 'CategoryController@ajaxSelectCategory')->name('ajaxSelectCategory');
    Route::put('table-category-position', 'CategoryController@ajaxTableCategory')->name('ajaxTableCategory');
    Route::post('select-position-position', 'PositionController@ajaxSelectPosition')->name('ajaxSelectPosition');
    Route::put('table-position-position', 'PositionController@ajaxTablePosition')->name('ajaxTablePosition');
    Route::post('select-position-image', 'ImageController@ajaxSelectPositionImages')->name('ajaxSelectPositionImages');
    Route::post('select-attribute-position', 'AttributeController@ajaxSelectAttribute')->name('ajaxSelectAttribute');

    Route::post('add-notification','AjaxController@addNotification')->name('addNotification');
    Route::post('make-as-read','AjaxController@MakeAsReadNoti')->name('MakeAsReadNoti');
    Route::post('add-row-upload-image', 'AjaxController@addRowUploadImage')->name('addRowUploadImage');
    Route::post('add-row-upload-attribute', 'AjaxController@addRowUploadAttribute')->name('addRowUploadAttribute');
    Route::post('get-district', 'AjaxController@getDistrict')->name('getDistrict');
    Route::post('get-ward', 'AjaxController@getWard')->name('getWard');
});

Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('lang/{locale}', 'DashboardController@locale')->name('locale');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')->name('ckfinder_connector');
Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')->name('ckfinder_browser');

Route::get('/', function () {
    $data['config'] = DB::table('configs')->pluck('value', 'attribute')->toArray();
    // dd(file_get_contents(base_path("route/admin.php")));
    return view('welcome',$data);
})->name('index');

Route::get('/orderId/{orderid}',function () {
    $data['config'] = DB::table('configs')->pluck('value', 'attribute')->toArray();
    return view('welcome',$data);
})->name('orderId');
Route::get('/payment_success', 'TestPayment@getStatusCode')->name('pay_success');

Route::post('/created_order','TestPayment@createOrder')->name('created_order');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use App\Notifications\VerificationEmail;
use Illuminate\Notifications\Notifiable;
use App\Notifications\ForgotPasswordEmail;
use Rennokki\QueryCache\Traits\QueryCacheable;
use Askedio\SoftCascade\Traits\SoftCascadeTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens, HasRoles, SoftCascadeTrait, QueryCacheable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * equivalent of ->cacheTags(['users'])
     * @var string
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
    */
    public $cacheTags = ['users'];
    /**
     * equivalent of ->cachePrefix('users_');
     * @var string
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
    */
    public $cachePrefix = 'users_';
    /**
     * Invalidate the cache automatically
     * upon update in the database.
     *
     * @var bool
     */
    protected static $flushCacheOnUpdate = true;

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The attributes date.
     *
     * @var array
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    protected $dates = ['created_at', 'updated_at'];

    /**
     * The attributes soft delete with function name.
     * @var array
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    protected $softCascade = [];

    /**
     * Auto running on models
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->uuid = (string)Str::uuid();
        });
    }

    /**
     * Send the user a verification email
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function sendVerificationEmail()
    {
        $this->notify(new VerificationEmail($this));
    }

    /**
     * Send email forgot password with token
     * @param string $token
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function sendForgotPasswordEmail(string $token)
    {
        $this->notify(new ForgotPasswordEmail($this, $token));
    }
}

resources/views/administrator/modules/user/actions.blade.php
<div class="list-icons">
    <div class="dropdown">
        <a href="#" class="list-icons-item" data-toggle="dropdown">
            <i class="icon-menu9"></i>
        </a>

        <div class="dropdown-menu dropdown-menu-right">
            @can('user_edit')
                <a href="{{ route('admin.user.edit', ['user' => $uuid]) }}" class="dropdown-item text-info"><i class="icon-pencil"></i> {{ behavior('action.edit') }}</a>
            @endcan

            @can('user_destroy')
                <a href="{{ route('admin.user.destroy', ['user' => $uuid]) }}" class="dropdown-item accept_delete text-danger"><i class="icon-trash"></i> {{ behavior('action.delete') }}</a>
            @endcan
        </div>
    </div>
</div>

resources/views/administrator/modules/user/create.blade.php
@extends('administrator.master')
@section('module', module('user'))
@section('action', behavior('action.create'))
@section('title', title_module('user', 'create'))

@canany(['user_index', 'user_edit', 'user_destroy'])
    @section('index', route('admin.user.index'))
@endcanany

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'ui/dragula.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/switch.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'editors/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'media/fancybox.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    @include('ckfinder::setup')
@endpush

@section('content')
    <form action="{{ route('admin.user.store') }}" method="POST" enctype="multipart/form-data" class="formAjax">
        @csrf
        @method('POST')

        <div class="row">
            @include('administrator.partials.button', ['exit' => route('admin.user.index')])

            <div class="col-lg-8">
                <x-card title="action.info" id="forms-target-left">
                    <x-text label="user.email" type="email" name="email" placeholder="user.email" required="required">
                        {{ old('email') }}
                    </x-text>

                    <x-text label="user.password" type="password" name="password" placeholder="user.password" required="required">
                        {{ old('password') }}
                    </x-text>

                    <x-text label="user.password_confirm" type="password" name="password_confirmation" placeholder="user.password_confirm" required="required">
                        {{ old('password_confirm') }}
                    </x-text>
                </x-card>

                <x-card title="action.info" id="forms-target-left">
                    <x-text label="user.full_name" name="full_name" placeholder="user.full_name" required="required">
                        {{ old('full_name') }}
                    </x-text>

                    <x-text label="user.phone" name="phone" placeholder="user.phone" required="required">
                        {{ old('phone') }}
                    </x-text>

                    <x-text label="user.address" name="address" placeholder="user.address" required="required">
                        {{ old('address') }}
                    </x-text>
                </x-card>
            </div>

            <div class="col-lg-4">
                <x-card title="action.info" id="forms-target-right">
                    <x-selectbox label="user.level" name="level" :dataSelect="level()" required="required">
                        {{ old('level') }}
                    </x-selectbox>

                    <div id="user_role">
                        <x-selectbox label="user.permission" name="role_id" :dataSelect="$roles" required="required">
                            {{ old('role_id') }}
                        </x-selectbox>
                    </div>

                    <x-image name="avatar">
                        {{ old('avatar') }}
                    </x-image>

                    <x-toggle label="element.status" name="status" on="element.status_enable" off="element.status_disable" required="required">
                        {{ old('status','on') }}
                    </x-toggle>
                </x-card>
            </div>
        </div>
    </form>
@endsection

resources/views/administrator/modules/user/edit.blade.php
@extends('administrator.master')
@section('module', module('user'))
@section('action', behavior('action.edit'))
@section('title', title_module('user', 'edit'))

@canany(['user_index', 'user_edit', 'user_destroy'])
    @section('index', route('admin.user.index'))
@endcanany

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'ui/dragula.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/switch.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'editors/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'media/fancybox.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    @include('ckfinder::setup')
@endpush

@section('content')
    <form action="{{ route('admin.user.update', ['user' => $user->uuid]) }}" method="POST" enctype="multipart/form-data" class="formAjax">
        @csrf
        @method('PUT')

        <div class="row">
            @include('administrator.partials.button', ['exit' => route('admin.user.index')])

            <div class="col-lg-8">
                <x-card title="action.info" id="forms-target-left">
                    <x-text label="user.email" type="email" disabled="disabled" name="email" placeholder="user.email" required="required">
                        {{ old('email', $user->email) }}
                    </x-text>

                    <x-text label="user.password" type="password" name="password" placeholder="user.password" required="required">
                        {{ old('password') }}
                    </x-text>

                    <x-text label="user.password_confirm" type="password" name="password_confirmation" placeholder="user.password_confirm" required="required">
                        {{ old('password_confirm') }}
                    </x-text>
                </x-card>

                <x-card title="action.info" id="forms-target-left">
                    <x-text label="user.full_name" name="full_name" placeholder="user.full_name" required="required">
                        {{ old('full_name', $user->full_name) }}
                    </x-text>

                    <x-text label="user.phone" name="phone" placeholder="user.phone" required="required">
                        {{ old('phone', $user->phone) }}
                    </x-text>

                    <x-text label="user.address" name="address" placeholder="user.address" required="required">
                        {{ old('address', $user->address) }}
                    </x-text>
                </x-card>
            </div>

            <div class="col-lg-4">
                <x-card title="action.info" id="forms-target-right">
                    <x-selectbox label="user.level" name="level" :dataSelect="level()" required="required">
                        {{ old('level', $user->level) }}
                    </x-selectbox>

                    <div id="user_role">
                        <x-selectbox label="user.permission" name="role_id" :dataSelect="$roles" required="required">
                            {{ old('role_id', $pemission_current) }}
                        </x-selectbox>
                    </div>

                    <x-image name="avatar">
                        {{ old('avatar', $user->avatar) }}
                    </x-image>

                    <x-toggle label="element.status" name="status" on="element.status_enable" off="element.status_disable" required="required">
                        {{ old('status', $user->status) }}
                    </x-toggle>
                </x-card>
            </div>
        </div>
    </form>
@endsection

resources/views/administrator/modules/user/index.blade.php
@extends('administrator.master')
@section('module', module('user'))
@section('action', behavior('action.index'))
@section('title', title_module('user','index'))

@can('user_create')
    @section('create', route('admin.user.create'))
@endcan

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/extensions/buttons.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/extensions/responsive.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
@endpush

@section('content')
    <x-card title="action.info" table="true">
        <table class="table table-hover datatable-colvis-basic" url="{{ route('admin.ajax.userDataTables') }}">
            <thead>
                <tr>
                    <th>{{ label('user.avatar') }}</th>
                    <th>{{ label('user.email') }}</th>
                    <th>{{ label('user.full_name') }}</th>
                    <th>{{ label('user.level') }}</th>
                    <th>{{ label('element.status') }}</th>
                    @canany(['user_edit', 'user_destroy'])
                        <th class="text-center">{{ label('element.actions') }}</th>
                    @endcanany
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th data="avatar" name="avatar">{{ label('user.avatar') }}</th>
                    <th type="text" data="email" name="email">{{ label('user.email') }}</th>
                    <th type="text" data="full_name" name="full_name">{{ label('user.full_name') }}</th>
                    <th type="select" data="level" name="level">
                        <select class="form-control filter-select">
                            <option value="">{{ label('please_choose') }}</option>
                            @foreach (level() as $level)
                                <option value="{{ $level->id }}">{{ $level->name }}</option>
                            @endforeach
                        </select>
                    </th>
                    <th type="select" data="status" name="status">
                        <select class="form-control filter-select">
                            <option value="">{{ label('please_choose') }}</option>
                            <option value="on">{{ label('element.status_enable') }}</option>
                            <option value="off">{{ label('element.status_disable') }}</option>
                        </select>
                    </th>
                    @canany(['user_edit', 'user_destroy'])
                        <th class="text-center" data="actions" name="actions" orderable="false" searchable="false">{{ label('element.actions') }}</th>
                    @endcanany
                </tr>
            </tfoot>
        </table>
    </x-card>
@endsection