routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::prefix('content')->name('content.')->group(function () {
    Route::get('{page}', 'ContentController@index')->name('index');
    Route::get('{page}/create', 'ContentController@create')->name('create');
    Route::post('{page}', 'ContentController@store')->name('store');
    Route::get('{page}/{content}/edit', 'ContentController@edit')->name('edit');
    Route::put('{page}/{content}', 'ContentController@update')->name('update');
    Route::delete('{page}/{content}', 'ContentController@destroy')->name('destroy');
});

//Bind Route
Route::resource('language', 'LanguageController');
Route::resource('page', 'PageController');
Route::resource('role', 'RoleController');
Route::resource('user', 'UserController');
Route::resource('category', 'CategoryController');
Route::resource('news', 'NewsController');
Route::resource('position', 'PositionController');
Route::resource('image', 'ImageController');
Route::resource('cart', 'CartController');
Route::resource('province', 'ProvinceController');
Route::resource('district', 'DistrictController');
Route::resource('ward', 'WardController');
Route::resource('producer', 'ProducerController');
Route::resource('attribute', 'AttributeController');
Route::resource('product', 'ProductController');
Route::resource('backup', 'BackupController')->except(['edit', 'update', 'show']);
Route::resource('activity', 'LogActivityController')->only(['index', 'destroy']);
Route::get('backup/download/{backup}','BackupController@download')->name('backup.download');

Route::prefix('config')->name('config.')->group(function () {
    Route::get('/', 'ConfigController@edit')->name('edit');
    Route::put('update', 'ConfigController@update')->name('update');
});

Route::prefix('page')->name('page.')->group(function () {
    Route::get('page-translation/{page}', 'PageController@language')->name('language');
    Route::post('page-translation/{page}', 'PageController@translation')->name('translation');
});

Route::prefix('content')->name('content.')->group(function () {
    Route::get('translation/{page}/{content}', 'ContentController@language')->name('language');
    Route::post('translation/{page}/{content}', 'ContentController@translation')->name('translation');
});

Route::prefix('category')->name('category.')->group(function () {
    Route::get('translation/{category}', 'CategoryController@language')->name('language');
    Route::post('translation/{category}', 'CategoryController@translation')->name('translation');
});

Route::prefix('image')->name('image.')->group(function () {
    Route::get('translation/{image}', 'ImageController@language')->name('language');
    Route::post('translation/{image}', 'ImageController@translation')->name('translation');
});

Route::prefix('producer')->name('producer.')->group(function () {
    Route::get('translation/{producer}', 'ProducerController@language')->name('language');
    Route::post('translation/{producer}', 'ProducerController@translation')->name('translation');
});

Route::prefix('attribute')->name('attribute.')->group(function () {
    Route::get('translation/{attribute}', 'AttributeController@language')->name('language');
    Route::post('translation/{attribute}', 'AttributeController@translation')->name('translation');
});

Route::prefix('news')->name('news.')->group(function () {
    Route::get('translation/{news}', 'NewsController@language')->name('language');
    Route::post('translation/{news}', 'NewsController@translation')->name('translation');
    Route::get('detail/{news}', 'NewsController@detail')->name('detail');
    Route::get('seo/{news}', 'NewsController@seo')->name('seo');
});

Route::prefix('product')->name('product.')->group(function () {
    Route::get('translation/{product}', 'ProductController@language')->name('language');
    Route::post('translation/{product}', 'ProductController@translation')->name('translation');
});

Route::prefix('contact')->name('contact.')->group(function () {
    Route::get('/', 'ReplyContactController@index')->name('index');
    Route::get('reply/{contact}', 'ReplyContactController@reply')->name('reply');
    Route::post('reply/{contact}', 'ReplyContactController@send_reply')->name('send_reply');
    Route::delete('reply/{contact}', 'ReplyContactController@destroy')->name('destroy');
});

Route::prefix('personal')->name('personal.')->group(function () {
    Route::get('/', 'PersonalController@show')->name('show');
    Route::put('update-account', 'PersonalController@update_account')->name('update_account');
    Route::put('update-avatar', 'PersonalController@update_avatar')->name('update_avatar');
    Route::put('update-info', 'PersonalController@update_info')->name('update_info');
    Route::get('logout', 'PersonalController@logout')->name('logout');
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    //Bind Datatables
    Route::get('role-datatables', 'RoleController@dataTableIndex')->name('roleDataTables');
    Route::get('user-datatables', 'UserController@dataTableIndex')->name('userDataTables');
    Route::get('language-datatables', 'LanguageController@dataTableIndex')->name('languageDataTables');
    Route::get('personal-datatables', 'PersonalController@dataTableIndex')->name('personalDataTables');
    Route::get('get-cart', 'CartController@dataTableIndex')->name('CartController');
    Route::get('news-datatables', 'NewsController@dataTableIndex')->name('newsDataTables');
    Route::get('images-datatables', 'ImageController@dataTableIndex')->name('imageDataTables');
    Route::get('page-datatables', 'PageController@dataTableIndex')->name('pageDataTables');
    Route::get('contact-datatables', 'ReplyContactController@dataTableIndex')->name('contactDataTables');
    Route::get('content-datatables/{page}', 'ContentController@dataTableIndex')->name('contentDataTables');
    Route::get('activity-datatables', 'LogActivityController@dataTableIndex')->name('activityDataTables');
    Route::get('province-datatables', 'ProvinceController@dataTableIndex')->name('provinceDataTables');
    Route::get('district-datatables', 'DistrictController@dataTableIndex')->name('districtDataTables');
    Route::get('ward-datatables', 'WardController@dataTableIndex')->name('wardDataTables');
    Route::get('producer-datatables', 'ProducerController@dataTableIndex')->name('producerDataTables');
    Route::get('attribute-datatables', 'AttributeController@dataTableIndex')->name('attributeDataTables');
    Route::get('product-datatables', 'ProductController@dataTableIndex')->name('productDataTables');
    Route::post('get-district-by-province', 'WardController@loadDistrict')->name('loadDistrict');

    Route::post('select-category-position', 'CategoryController@ajaxSelectCategory')->name('ajaxSelectCategory');
    Route::put('table-category-position', 'CategoryController@ajaxTableCategory')->name('ajaxTableCategory');
    Route::post('select-position-position', 'PositionController@ajaxSelectPosition')->name('ajaxSelectPosition');
    Route::put('table-position-position', 'PositionController@ajaxTablePosition')->name('ajaxTablePosition');
    Route::post('select-position-image', 'ImageController@ajaxSelectPositionImages')->name('ajaxSelectPositionImages');
    Route::post('select-attribute-position', 'AttributeController@ajaxSelectAttribute')->name('ajaxSelectAttribute');

    Route::post('add-notification','AjaxController@addNotification')->name('addNotification');
    Route::post('make-as-read','AjaxController@MakeAsReadNoti')->name('MakeAsReadNoti');
    Route::post('add-row-upload-image', 'AjaxController@addRowUploadImage')->name('addRowUploadImage');
    Route::post('add-row-upload-attribute', 'AjaxController@addRowUploadAttribute')->name('addRowUploadAttribute');
    Route::post('get-district', 'AjaxController@getDistrict')->name('getDistrict');
    Route::post('get-ward', 'AjaxController@getWard')->name('getWard');
});

Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('lang/{locale}', 'DashboardController@locale')->name('locale');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')->name('ckfinder_connector');
Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')->name('ckfinder_browser');

Route::get('/', function () {
    $data['config'] = DB::table('configs')->pluck('value', 'attribute')->toArray();
    // dd(file_get_contents(base_path("route/admin.php")));
    return view('welcome',$data);
})->name('index');

Route::get('/orderId/{orderid}',function () {
    $data['config'] = DB::table('configs')->pluck('value', 'attribute')->toArray();
    return view('welcome',$data);
})->name('orderId');
Route::get('/payment_success', 'TestPayment@getStatusCode')->name('pay_success');

Route::post('/created_order','TestPayment@createOrder')->name('created_order');

app/Http/Controllers/Administrator/DistrictController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Models\District;
use Yajra\DataTables\DataTables;
use App\Helpers\LogActivityHelper;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Request;
use Illuminate\Database\Eloquent\Builder;
use App\Repositories\District\DistrictRepository;
use App\Repositories\Province\ProvinceRepository;
use App\Http\Resources\District as DistrictResource;
use App\Http\Controllers\Administrator\AdminController;
use App\Http\Requests\Administrator\District\StoreRequest;
use App\Http\Requests\Administrator\District\UpdateRequest;

class DistrictController extends AdminController
{
    private $view = 'administrator.modules.district.';

    private $route = 'admin.district.';

    private $module = 'module.district';

    private $province;

    private $district;

    /**
     * DistrictController constructor.
     * @param ProvinceRepository $province
     * @param DistrictRepository $district
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function __construct(ProvinceRepository $province,
                                DistrictRepository $district)
    {
        parent::__construct();
        $this->middleware('permission:district_index', ['only' => ['show', 'index', 'dataTableIndex']]);
        $this->middleware('permission:district_create', ['only' => ['create', 'store']]);
        $this->middleware('permission:district_edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:district_destroy', ['only' => ['destroy']]);
        $this->province = $province;
        $this->district = $district;
    }

    /**
     * Display a listing of the resource.
     *
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function index()
    {
        if (Request::is('api*')) {
            $district = $this->district->getAll();
            return new DistrictResource($district);
        }

        return view($this->view . 'index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function create()
    {
        $data['provinces'] = $this->province->getAll();
        return view($this->view . 'create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreRequest $request
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function store(StoreRequest $request)
    {
        $data             = $request->except(['_token', '_method']);
        $data['status']   = $request->status ?? 'off';
        $data['featured'] = $request->default ?? 'off';
        $result           = $this->district->create($data);

        District::flushQueryCache(['districts']);

        LogActivityHelper::addToLog([
            'module'      => 'district',
            'action'      => 'create',
            'description' => $request->name
        ]);

        return response()->json(
            [
                'status'   => 'success',
                'message'  => message_module($this->module, 'crud.create_success'),
                'redirect' => route($this->route . 'create'),
                'result'   => $result
            ], 201);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function show(int $id)
    {
        $result = $this->district->getById($id);

        return response()->json(
            [
                'status' => 'success',
                'result' => $result
            ], 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function edit(int $id)
    {
        $data['provinces'] = $this->province->getAll();
        $data['district']  = $this->district->getById($id);

        return view($this->view . 'edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param int $id
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function update(UpdateRequest $request, int $id)
    {
        $data             = $request->except(['_token', '_method']);
        $data['status']   = $request->status ?? 'off';
        $data['featured'] = $request->featured ?? 'off';
        $result           = $this->district->update($data, $id, false);

        District::flushQueryCache(['districts']);

        LogActivityHelper::addToLog([
            'module'      => 'district',
            'action'      => 'edit',
            'description' => $request->name
        ]);

        return response()->json(
            [
                'status'   => 'success',
                'message'  => message_module($this->module, 'crud.edit_success'),
                'redirect' => route($this->route . 'edit', ['district' => $id]),
                'result'   => $result
            ], 201);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function destroy(int $id)
    {
        $data = $this->district->getById($id);

        District::flushQueryCache(['districts']);

        LogActivityHelper::addToLog([
            'module'      => 'province',
            'action'      => 'delete',
            'description' => $data->name
        ]);

        $result = $this->district->remove($id, false);

        return response()->json(
            [
                'status'  => 'success',
                'message' => message_module($this->module, 'crud.destroy_success'),
                'result'  => $result,
            ], 200);
    }

    /**
     * Process datatables ajax request.
     * @return mixed
     * @throws \Exception
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function dataTableIndex()
    {
        $district = $this->district->query()->whereNull('deleted_at');

        return Datatables::of($district)
            ->editColumn('provinces', function ($district) {
                $provinces = DB::table('provinces')
                    ->where('id', $district->province_id)
                    ->whereNull('deleted_at')
                    ->first();

                return $provinces->name;
            })
            ->filterColumn('provinces', function(Builder $query ,$keyword) {
                $query->whereHas('province', function (Builder $query) use ($keyword) {
                    $query->where('provinces.name','like', "%{$keyword}%");
                });
            })
            ->editColumn('status', function ($language) {
                if ($language->status == 'on') {
                    $xhtml = '<span class="badge btn-xs badge-info">' . label('element.status_enable') . '</span>';
                } else {
                    $xhtml = '<span class="badge badge-secondary">' . label('element.status_disable') . '</span>';

                }
                return $xhtml;
            })
            ->addColumn('actions', 'administrator.modules.district.actions')
            ->rawColumns(['status', 'actions'])
            ->addIndexColumn()
            ->make(true);
    }
}

resources/views/administrator/modules/district/actions.blade.php
<div class="list-icons">
    <div class="dropdown">
        <a href="#" class="list-icons-item" data-toggle="dropdown">
            <i class="icon-menu9"></i>
        </a>

        <div class="dropdown-menu dropdown-menu-right">
            @can('district_edit')
                <a href="{{ route('admin.district.edit', ['district' => $id]) }}" class="dropdown-item text-info"><i class="icon-pencil"></i> {{ behavior('action.edit') }}</a>
            @endcan

            @can('district_destroy')
                <a href="{{ route('admin.district.destroy', ['district' => $id]) }}" class="dropdown-item accept_delete text-danger"><i class="icon-trash"></i> {{ behavior('action.delete') }}</a>
            @endcan
        </div>
    </div>
</div>

resources/views/administrator/modules/district/create.blade.php
@extends('administrator.master')
@section('module', module('district'))
@section('action', behavior('action.create'))
@section('title', title_module('district', 'create'))

@canany(['district_index', 'district_edit', 'district_destroy'])
    @section('index', route('admin.district.index'))
@endcanany

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'ui/dragula.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/switch.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'media/fancybox.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    @include('ckfinder::setup')
@endpush

@section('content')
    <form action="{{ route('admin.district.store') }}" method="POST" enctype="multipart/form-data" class="formAjax">
        @csrf
        @method('POST')

        <div class="row">
            @include('administrator.partials.button', ['exit' => route('admin.district.index')])

            <div class="col-lg-8">
                <x-card title="action.info" id="forms-target-left">
                    <x-selectbox label="province.name" name="province_id" :dataSelect="$provinces" required="required">
                        {{ old('province_id') }}
                    </x-selectbox>

                    <x-text label="district.gso_id" type="text" name="gso_id" placeholder="district.gso_id" required="required">
                        {{ old('gso_id') }}
                    </x-text>

                    <x-text label="district.name" type="text" name="name" placeholder="district.name" required="required">
                        {{ old('name') }}
                    </x-text>
                </x-card>
            </div>

            <div class="col-lg-4">
                <x-card title="action.info" id="forms-target-right">
                    <x-toggle label="element.status" name="status" on="element.status_enable" off="element.status_disable" required="required">
                        {{ old('status','on') }}
                    </x-toggle>

                    <x-toggle label="element.featured" name="featured" on="element.default_yes" off="element.default_no" required="required">
                        {{ old('featured','off') }}
                    </x-toggle>
                </x-card>
            </div>
        </div>
    </form>
@endsection

resources/views/administrator/modules/district/edit.blade.php
@extends('administrator.master')
@section('module', module('district'))
@section('action', behavior('action.edit'))
@section('title', title_module('district', 'edit'))

@canany(['district_index', 'district_edit', 'district_destroy'])
    @section('index', route('admin.district.index'))
@endcanany

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'ui/dragula.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/switch.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'media/fancybox.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    @include('ckfinder::setup')
@endpush

@section('content')
    <form action="{{ route('admin.district.update', ['district' => $district->id]) }}" method="POST" enctype="multipart/form-data" class="formAjax">
        @csrf
        @method('PUT')

        <div class="row">
            @include('administrator.partials.button', ['exit' => route('admin.district.index')])

            <div class="col-lg-8">
                <x-card title="action.info" id="forms-target-left">
                    <x-selectbox label="province.name" name="province_id" :dataSelect="$provinces" required="required">
                        {{ old('province_id', $district->province_id) }}
                    </x-selectbox>

                    <x-text label="district.gso_id" type="text" name="gso_id" placeholder="district.gso_id" required="required">
                        {{ old('gso_id', $district->gso_id) }}
                    </x-text>

                    <x-text label="district.name" type="text" name="name" placeholder="district.name" required="required">
                        {{ old('name', $district->name) }}
                    </x-text>
                </x-card>
            </div>

            <div class="col-lg-4">
                <x-card title="action.info" id="forms-target-right">
                    <x-toggle label="element.status" name="status" on="element.status_enable" off="element.status_disable" required="required">
                        {{ old('status', $district->status) }}
                    </x-toggle>

                    <x-toggle label="element.featured" name="featured" on="element.default_yes" off="element.default_no" required="required">
                        {{ old('featured', $district->featured) }}
                    </x-toggle>
                </x-card>
            </div>
        </div>
    </form>
@endsection

resources/views/administrator/modules/district/index.blade.php
@extends('administrator.master')
@section('module', module('district'))
@section('action', behavior('action.index'))
@section('title', title_module('district', 'index'))

@can('district_create')
    @section('create', route('admin.district.create'))
@endcan

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/extensions/buttons.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/extensions/responsive.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/switch.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/noty.min.js') }}"></script>
@endpush

@section('content')
    <x-card title="action.info" table="true">
        <table class="table table-hover datatable-colvis-basic" url="{{ route('admin.ajax.districtDataTables') }}">
            <thead>
                <tr>
                    <th>{{ label('element.table_id') }}</th>
                    <th>{{ label('province.name') }}</th>
                    <th>{{ label('district.name') }}</th>
                    <th>{{ label('element.status') }}</th>
                    @canany(['district_edit', 'district_destroy'])
                        <th class="text-center">{{ label('element.actions') }}</th>
                    @endcanany
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th data="DT_RowIndex" name="DT_RowIndex" orderable="false" searchable="false"></th>
                    <th type="text" data="provinces" name="provinces">{{ label('province.name') }}</th>
                    <th type="text" data="name" name="name">{{ label('district.name') }}</th>
                    <th type="select" data="status" name="status">
                        <select class="form-control">
                            <option value="">{{ label('please_choose') }}</option>
                            <option value="on">{{ label('element.status_enable') }}</option>
                            <option value="off">{{ label('element.status_disable') }}</option>
                        </select>
                    </th>
                    @canany(['district_edit', 'district_destroy'])
                        <th class="text-center" data="actions" name="actions" orderable="false" searchable="false">{{ label('element.actions') }}</th>
                    @endcanany
                </tr>
            </tfoot>
        </table>
    </x-card>
@endsection