routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

Route::prefix('content')->name('content.')->group(function () {
    Route::get('{page}', 'ContentController@index')->name('index');
    Route::get('{page}/create', 'ContentController@create')->name('create');
    Route::post('{page}', 'ContentController@store')->name('store');
    Route::get('{page}/{content}/edit', 'ContentController@edit')->name('edit');
    Route::put('{page}/{content}', 'ContentController@update')->name('update');
    Route::delete('{page}/{content}', 'ContentController@destroy')->name('destroy');
});

//Bind Route
Route::resource('language', 'LanguageController');
Route::resource('page', 'PageController');
Route::resource('role', 'RoleController');
Route::resource('user', 'UserController');
Route::resource('category', 'CategoryController');
Route::resource('news', 'NewsController');
Route::resource('position', 'PositionController');
Route::resource('image', 'ImageController');
Route::resource('cart', 'CartController');
Route::resource('province', 'ProvinceController');
Route::resource('district', 'DistrictController');
Route::resource('ward', 'WardController');
Route::resource('producer', 'ProducerController');
Route::resource('attribute', 'AttributeController');
Route::resource('product', 'ProductController');
Route::resource('backup', 'BackupController')->except(['edit', 'update', 'show']);
Route::resource('activity', 'LogActivityController')->only(['index', 'destroy']);
Route::get('backup/download/{backup}','BackupController@download')->name('backup.download');

Route::prefix('config')->name('config.')->group(function () {
    Route::get('/', 'ConfigController@edit')->name('edit');
    Route::put('update', 'ConfigController@update')->name('update');
});

Route::prefix('page')->name('page.')->group(function () {
    Route::get('page-translation/{page}', 'PageController@language')->name('language');
    Route::post('page-translation/{page}', 'PageController@translation')->name('translation');
});

Route::prefix('content')->name('content.')->group(function () {
    Route::get('translation/{page}/{content}', 'ContentController@language')->name('language');
    Route::post('translation/{page}/{content}', 'ContentController@translation')->name('translation');
});

Route::prefix('category')->name('category.')->group(function () {
    Route::get('translation/{category}', 'CategoryController@language')->name('language');
    Route::post('translation/{category}', 'CategoryController@translation')->name('translation');
});

Route::prefix('image')->name('image.')->group(function () {
    Route::get('translation/{image}', 'ImageController@language')->name('language');
    Route::post('translation/{image}', 'ImageController@translation')->name('translation');
});

Route::prefix('producer')->name('producer.')->group(function () {
    Route::get('translation/{producer}', 'ProducerController@language')->name('language');
    Route::post('translation/{producer}', 'ProducerController@translation')->name('translation');
});

Route::prefix('attribute')->name('attribute.')->group(function () {
    Route::get('translation/{attribute}', 'AttributeController@language')->name('language');
    Route::post('translation/{attribute}', 'AttributeController@translation')->name('translation');
});

Route::prefix('news')->name('news.')->group(function () {
    Route::get('translation/{news}', 'NewsController@language')->name('language');
    Route::post('translation/{news}', 'NewsController@translation')->name('translation');
    Route::get('detail/{news}', 'NewsController@detail')->name('detail');
    Route::get('seo/{news}', 'NewsController@seo')->name('seo');
});

Route::prefix('product')->name('product.')->group(function () {
    Route::get('translation/{product}', 'ProductController@language')->name('language');
    Route::post('translation/{product}', 'ProductController@translation')->name('translation');
});

Route::prefix('contact')->name('contact.')->group(function () {
    Route::get('/', 'ReplyContactController@index')->name('index');
    Route::get('reply/{contact}', 'ReplyContactController@reply')->name('reply');
    Route::post('reply/{contact}', 'ReplyContactController@send_reply')->name('send_reply');
    Route::delete('reply/{contact}', 'ReplyContactController@destroy')->name('destroy');
});

Route::prefix('personal')->name('personal.')->group(function () {
    Route::get('/', 'PersonalController@show')->name('show');
    Route::put('update-account', 'PersonalController@update_account')->name('update_account');
    Route::put('update-avatar', 'PersonalController@update_avatar')->name('update_avatar');
    Route::put('update-info', 'PersonalController@update_info')->name('update_info');
    Route::get('logout', 'PersonalController@logout')->name('logout');
});

Route::prefix('ajax')->name('ajax.')->group(function () {
    //Bind Datatables
    Route::get('role-datatables', 'RoleController@dataTableIndex')->name('roleDataTables');
    Route::get('user-datatables', 'UserController@dataTableIndex')->name('userDataTables');
    Route::get('language-datatables', 'LanguageController@dataTableIndex')->name('languageDataTables');
    Route::get('personal-datatables', 'PersonalController@dataTableIndex')->name('personalDataTables');
    Route::get('get-cart', 'CartController@dataTableIndex')->name('CartController');
    Route::get('news-datatables', 'NewsController@dataTableIndex')->name('newsDataTables');
    Route::get('images-datatables', 'ImageController@dataTableIndex')->name('imageDataTables');
    Route::get('page-datatables', 'PageController@dataTableIndex')->name('pageDataTables');
    Route::get('contact-datatables', 'ReplyContactController@dataTableIndex')->name('contactDataTables');
    Route::get('content-datatables/{page}', 'ContentController@dataTableIndex')->name('contentDataTables');
    Route::get('activity-datatables', 'LogActivityController@dataTableIndex')->name('activityDataTables');
    Route::get('province-datatables', 'ProvinceController@dataTableIndex')->name('provinceDataTables');
    Route::get('district-datatables', 'DistrictController@dataTableIndex')->name('districtDataTables');
    Route::get('ward-datatables', 'WardController@dataTableIndex')->name('wardDataTables');
    Route::get('producer-datatables', 'ProducerController@dataTableIndex')->name('producerDataTables');
    Route::get('attribute-datatables', 'AttributeController@dataTableIndex')->name('attributeDataTables');
    Route::get('product-datatables', 'ProductController@dataTableIndex')->name('productDataTables');
    Route::post('get-district-by-province', 'WardController@loadDistrict')->name('loadDistrict');

    Route::post('select-category-position', 'CategoryController@ajaxSelectCategory')->name('ajaxSelectCategory');
    Route::put('table-category-position', 'CategoryController@ajaxTableCategory')->name('ajaxTableCategory');
    Route::post('select-position-position', 'PositionController@ajaxSelectPosition')->name('ajaxSelectPosition');
    Route::put('table-position-position', 'PositionController@ajaxTablePosition')->name('ajaxTablePosition');
    Route::post('select-position-image', 'ImageController@ajaxSelectPositionImages')->name('ajaxSelectPositionImages');
    Route::post('select-attribute-position', 'AttributeController@ajaxSelectAttribute')->name('ajaxSelectAttribute');

    Route::post('add-notification','AjaxController@addNotification')->name('addNotification');
    Route::post('make-as-read','AjaxController@MakeAsReadNoti')->name('MakeAsReadNoti');
    Route::post('add-row-upload-image', 'AjaxController@addRowUploadImage')->name('addRowUploadImage');
    Route::post('add-row-upload-attribute', 'AjaxController@addRowUploadAttribute')->name('addRowUploadAttribute');
    Route::post('get-district', 'AjaxController@getDistrict')->name('getDistrict');
    Route::post('get-ward', 'AjaxController@getWard')->name('getWard');
});

Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('lang/{locale}', 'DashboardController@locale')->name('locale');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('/ckfinder/connector', '\CKSource\CKFinderBridge\Controller\CKFinderController@requestAction')->name('ckfinder_connector');
Route::any('/ckfinder/browser', '\CKSource\CKFinderBridge\Controller\CKFinderController@browserAction')->name('ckfinder_browser');

Route::get('/', function () {
    $data['config'] = DB::table('configs')->pluck('value', 'attribute')->toArray();
    // dd(file_get_contents(base_path("route/admin.php")));
    return view('welcome',$data);
})->name('index');

Route::get('/orderId/{orderid}',function () {
    $data['config'] = DB::table('configs')->pluck('value', 'attribute')->toArray();
    return view('welcome',$data);
})->name('orderId');
Route::get('/payment_success', 'TestPayment@getStatusCode')->name('pay_success');

Route::post('/created_order','TestPayment@createOrder')->name('created_order');

app/Http/Controllers/Administrator/RoleController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Helpers\LogActivityHelper;
use App\Http\Requests\Administrator\Role\StoreRequest;
use App\Http\Requests\Administrator\Role\UpdateRequest;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Yajra\DataTables\DataTables;

class RoleController extends AdminController
{
    private $route = 'admin.role.';

    private $view = 'administrator.modules.role.';

    private $module = 'module.role';

    /**
     * RoleController constructor.
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function __construct()
    {
        parent::__construct();
        $this->middleware('permission:role_index', ['only' => ['show', 'index', 'dataTableIndex']]);
        $this->middleware('permission:role_create', ['only' => ['create', 'store']]);
        $this->middleware('permission:role_edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:role_destroy', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function index()
    {
        return view($this->view . 'index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function create()
    {
        return view($this->view . 'create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreRequest $request
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function store(StoreRequest $request)
    {
        $data_role = array(
            'name'        => $request->name,
            'guard_name'  => 'web',
            'description' => $request->description,
            'status'      => $request->status ?? 'off'
        );

        $role = Role::create($data_role);

        foreach ($request->permission as $item) {
            $permissions = Permission::firstOrCreate(['name' => $item, 'guard_name' => 'web']);
            $role->givePermissionTo($permissions);
        }

        $result = Role::findByName($role->name)->permissions;

        LogActivityHelper::addToLog([
            'module'      => 'role',
            'action'      => 'create',
            'description' => $request->name
        ]);

        return response()->json(
            [
                'status'   => 'success',
                'message'  => message_module($this->module, 'crud.create_success'),
                'redirect' => route($this->route . 'create'),
                'result'   => $result
            ], 201);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function show($id)
    {
        $data['role']            = Role::findById($id);
        $data['permission_edit'] = Role::findById($id)->permissions->pluck('name')->toArray();

        return response()->json(
            [
                'status' => 'success',
                'result' => $data
            ], 200);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function edit($id)
    {
        $data['role']            = Role::findById($id);
        $data['permission_edit'] = Role::findById($id)->permissions->pluck('name')->toArray();
        return view($this->view . 'edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param int $id
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function update(UpdateRequest $request, $id)
    {
        $role = Role::findById($id);

        $data_role = array(
            'name'        => $request->name,
            'guard_name'  => 'web',
            'description' => $request->description,
            'status'      => $request->status ?? 'off'
        );

        $role->update($data_role);

        DB::table('role_has_permissions')->where('role_id', $id)->delete();

        foreach ($request->permission as $item) {
            $permissions = Permission::firstOrCreate(['name' => $item, 'guard_name' => 'web']);
            $role->givePermissionTo($permissions);
        }

        $result = Role::findByName($request->name)->permissions;

        LogActivityHelper::addToLog([
            'module'      => 'role',
            'action'      => 'edit',
            'description' => $request->name
        ]);

        return response()->json(
            [
                'status'   => 'success',
                'message'  => message_module($this->module, 'crud.edit_success'),
                'redirect' => route($this->route . 'edit', ['role' => $id]),
                'result'   => $result
            ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return mixed
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function destroy($id)
    {
        $totalModelHasRole = DB::table('model_has_roles')->where('role_id', $id)->count();

        if ($totalModelHasRole > 0) {
            return response()->json(
                [
                    'status'  => 'warning',
                    'message' => message_module($this->module, 'role.role_have_model'),
                ], 200);
        } else {
            $data = Role::findById($id);

            LogActivityHelper::addToLog([
                'module'      => 'role',
                'action'      => 'delete',
                'description' => $data->name,
            ]);

            $result = Role::destroy($id);

            return response()->json(
                [
                    'status'  => 'success',
                    'message' => message_module($this->module, 'crud.destroy_success'),
                    'result'  => $result
                ], 200);
        }
    }

    /**
     * Process datatables ajax request.
     * @return string
     * @throws \Exception
     * @author Quốc Tuấn <contact.quoctuan@gmail.com>
     */
    public function dataTableIndex()
    {
        $role = DB::table('roles')
            ->select(['id', 'name', 'status', 'created_at'])
            ->orderBy('created_at', 'DESC');

        return Datatables::of($role)
            ->editColumn('created_at', function ($role) {
                return $role->created_at;
            })
            ->editColumn('status', function ($role) {
                if ($role->status == 'on') {
                    $xhtml = '<span class="badge btn-xs badge-info">' . label('element.status_enable') . '</span>';
                } else {
                    $xhtml = '<span class="badge badge-secondary">' . label('element.status_disable') . '</span>';

                }
                return $xhtml;
            })
            ->addColumn('actions', 'administrator.modules.role.actions')
            ->rawColumns(['status', 'actions'])
            ->addIndexColumn()
            ->make(true);
    }
}

resources/views/administrator/modules/role/actions.blade.php
<div class="list-icons">
    <div class="dropdown">
        <a href="#" class="list-icons-item" data-toggle="dropdown">
            <i class="icon-menu9"></i>
        </a>

        <div class="dropdown-menu dropdown-menu-right">
            @can('role_edit')
            <a href="{{ route('admin.role.edit', ['role' => $id]) }}" class="dropdown-item text-info"><i class="icon-pencil"></i> {{ behavior('action.edit') }}</a>
            @endcan

            @can('role_destroy')
            <a href="{{ route('admin.role.destroy', ['role' => $id]) }}" class="dropdown-item accept_delete text-danger"><i class="icon-trash"></i> {{ behavior('action.delete') }}</a>
            @endcan
        </div>
    </div>
</div>

resources/views/administrator/modules/role/create.blade.php
@extends('administrator.master')
@section('module', module('role'))
@section('action', behavior('action.create'))
@section('title', title_module('role','create'))

@canany(['role_index', 'role_edit', 'role_destroy'])
    @section('index', route('admin.role.index'))
@endcanany

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'ui/dragula.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/switch.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'editors/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    @include('ckfinder::setup')
@endpush

@section('content')
    <form action="{{ route('admin.role.store') }}" method="POST" enctype="multipart/form-data" class="formAjax">
        @csrf
        @method('POST')

        <div class="row">
            @include('administrator.partials.button', ['exit' => route('admin.role.index')])

            <div class="col-lg-12">
                <x-card title="action.info" id="forms-target-left">
                    <x-text label="role.name" name="name" placeholder="role.name" required="required">
                        {{ old('name') }}
                    </x-text>

                    <x-editor label="role.description" name="description">
                        {{ old('description') }}
                    </x-editor>

                    <x-toggle label="element.status" name="status" on="element.status_enable"  off="element.status_disable" required="required">
                        {{ old('status','on') }}
                    </x-toggle>
                </x-card>
            </div>

            <div class="col-lg-12 mb-3">
                <div class="toast" style="opacity: 1; max-width: none;">
                    <div class="toast-body">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" name="check-all-permission" class="form-check-input-styled permission"/> {{ label('role.all_permission') }}
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            {{-- Generate role permission of module --}}
            @foreach (role_permissions() as $module => $permissions)
                <div class="col-lg-4">
                    <x-card :module="$module" id="forms-target-left">
                        <ul class="list-permission-parent">
                            <li>
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input type="checkbox" name="chkManage" class="form-check-input-styled permission" /> {{ label('role.permission_manage') }}
                                    </label>
                                </div>
                                <ul class="list-permission-child">
                                    @foreach ($permissions as $permission)
                                        <li>
                                            <div class="form-check">
                                                <label class="form-check-label">
                                                    <input type="checkbox" name="permission[]" class="form-check-input-styled permission" value="{{ $permission['value'] }}" {{ checkedRole (old('permission'), $permission['value']) }} /> {{ $permission['name'] }}
                                                </label>
                                            </div>
                                        </li>
                                    @endforeach
                                </ul>
                            </li>
                        </ul>
                    </x-card>
                </div>
            @endforeach
            {{-- ! End generate role permission of module --}}

        </div>
    </form>
@endsection

resources/views/administrator/modules/role/edit.blade.php
@extends('administrator.master')
@section('module', module('role'))
@section('action', behavior('action.edit'))
@section('title', title_module('role', 'edit'))

@canany(['role_index', 'role_edit', 'role_destroy'])
    @section('index', route('admin.role.index'))
@endcanany

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'ui/dragula.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/switch.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'editors/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    @include('ckfinder::setup')
@endpush

@section('content')
    <form action="{{ route('admin.role.update', ['role' => $role->id]) }}" method="POST" enctype="multipart/form-data" class="formAjax">
        @csrf
        @method('PUT')

        <div class="row">
            @include('administrator.partials.button', ['exit' => route('admin.role.index')])

            <div class="col-lg-12">
                <x-card title="action.info" id="forms-target-left">
                    <x-text label="role.name" name="name" placeholder="role.name" required="required">
                        {{ old('name', $role->name) }}
                    </x-text>

                    <x-editor label="role.description" name="description">
                        {{ old('description', $role->description) }}
                    </x-editor>

                    <x-toggle label="element.status" name="status" on="element.status_enable"  off="element.status_disable" required="required">
                        {{ old('status', $role->status) }}
                    </x-toggle>
                </x-card>
            </div>

            <div class="col-lg-12 mb-3">
                <div class="toast" style="opacity: 1; max-width: none;">
                    <div class="toast-body">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="checkbox" name="check-all-permission" class="form-check-input-styled permission"/> {{ label('role.all_permission') }}
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            {{-- Generate role permission of module --}}
            @foreach (role_permissions() as $module => $permissions)
                <div class="col-lg-4">
                    <x-card :module="$module" id="forms-target-left">
                        <ul class="list-permission-parent">
                            <li>
                                <div class="form-check">
                                    <label class="form-check-label">
                                        <input type="checkbox" name="chkManage" class="form-check-input-styled permission" /> {{ label('role.permission_manage') }}
                                    </label>
                                </div>
                                <ul class="list-permission-child">
                                    @foreach ($permissions as $permission)
                                        <li>
                                            <div class="form-check">
                                                <label class="form-check-label">
                                                    <input type="checkbox" name="permission[]" class="form-check-input-styled permission" value="{{ $permission['value'] }}" {{ checkedRole (old('permission', $permission_edit), $permission['value']) }} /> {{ $permission['name'] }}
                                                </label>
                                            </div>
                                        </li>
                                    @endforeach
                                </ul>
                            </li>
                        </ul>
                    </x-card>
                </div>
            @endforeach
            {{-- ! End generate role permission of module --}}

        </div>
    </form>
@endsection

resources/views/administrator/modules/role/index.blade.php
@extends('administrator.master')
@section('module', module('role'))
@section('action', behavior('action.index'))
@section('title', title_module('role', 'index'))

@can('role_create')
    @section('create', route('admin.role.create'))
@endcan

@push('themejs')
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/extensions/buttons.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'tables/datatables/extensions/responsive.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/sweet_alert.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'notifications/pnotify.min.js') }}"></script>
    <script src="{{ asset(GLOBAL_ASSETS_PLUG.'forms/selects/select2.min.js') }}"></script>
@endpush

@section('content')
    <x-card title="action.info" table="true">
        <table class="table table-hover datatable-colvis-basic" url="{{ route('admin.ajax.roleDataTables') }}">
            <thead>
                <tr>
                    <th>{{ label('element.table_id') }}</th>
                    <th>{{ label('role.name') }}</th>
                    <th>{{ label('element.status') }}</th>
                    <th>{{ label('element.created_at') }}</th>
                    @canany(['role_edit', 'role_destroy'])
                        <th class="text-center">{{ label('element.actions') }}</th>
                    @endcanany
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th data="DT_RowIndex" name="DT_RowIndex" orderable="false" searchable="false"></th>
                    <th type="text" data="name" name="name">{{ label('role.name') }}</th>
                    <th type="select" data="status" name="status">
                        <select class="form-control filter-select">
                            <option value="">{{ label('please_choose') }}</option>
                            <option value="on">{{ label('element.status_enable') }}</option>
                            <option value="off">{{ label('element.status_disable') }}</option>
                        </select>
                    </th>
                    <th type="text" data="created_at" name="created_at">{{ label('element.created_at') }}</th>
                    @canany(['role_edit', 'role_destroy'])
                        <th class="text-center" data="actions" name="actions" orderable="false" searchable="false">{{ label('element.actions') }}</th>
                    @endcanany
                </tr>
            </tfoot>
        </table>
    </x-card>
@endsection